import type { Game } from "@/types/game";

// Steam CDN — portrait box art (600x900) for cards, ultra-wide hero (3840x1240) for banners
const STEAM_COVER = (appId: number) =>
  `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/library_600x900.jpg`;
const STEAM_HERO = (appId: number) =>
  `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/library_hero.jpg`;

const IMG = {
  cyberpunk:   { cover: STEAM_COVER(1091500), hero: STEAM_HERO(1091500) },
  eldenRing:   { cover: STEAM_COVER(1245620), hero: STEAM_HERO(1245620) },
  gowRagnarok: { cover: STEAM_COVER(2322010), hero: STEAM_HERO(2322010) },
  baldursGate3: { cover: STEAM_COVER(1086940), hero: STEAM_HERO(1086940) },
  rdr2:        { cover: STEAM_COVER(1174180), hero: STEAM_HERO(1174180) },
  witcher3:    { cover: STEAM_COVER(292030),  hero: STEAM_HERO(292030) },
  spiderMan2:  { cover: STEAM_COVER(2651280), hero: STEAM_HERO(2651280) },
  re4Remake:   { cover: STEAM_COVER(2050650), hero: STEAM_HERO(2050650) },
  starfield:   { cover: STEAM_COVER(1716740), hero: STEAM_HERO(1716740) },
  horizonFW:   { cover: STEAM_COVER(2420110), hero: STEAM_HERO(2420110) },
  blackMyth:   { cover: STEAM_COVER(2358720), hero: STEAM_HERO(2358720) },
  zeldaTotK:   { cover: "/covers/zelda-totk.jpg", hero: "/covers/zelda-totk.jpg" },
  gta5:        { cover: STEAM_COVER(271590),  hero: STEAM_HERO(271590) },
  mhw:         { cover: STEAM_COVER(582010),  hero: STEAM_HERO(582010) },
  sekiro:      { cover: STEAM_COVER(814380),  hero: STEAM_HERO(814380) },
  darkSouls3:  { cover: STEAM_COVER(374320),  hero: STEAM_HERO(374320) },
  ghostTsushima: { cover: STEAM_COVER(2215430), hero: STEAM_HERO(2215430) },
  deathStranding: { cover: STEAM_COVER(1850570), hero: STEAM_HERO(1850570) },
  hades:       { cover: STEAM_COVER(1145360), hero: STEAM_HERO(1145360) },
  hogwarts:    { cover: STEAM_COVER(990080),  hero: STEAM_HERO(990080) },
  doomEternal: { cover: STEAM_COVER(782330),  hero: STEAM_HERO(782330) },
  stray:       { cover: STEAM_COVER(1332010), hero: STEAM_HERO(1332010) },
  ff7r:        { cover: STEAM_COVER(1462040), hero: STEAM_HERO(1462040) },
  diablo4:     { cover: STEAM_COVER(2344520), hero: STEAM_HERO(2344520) },
  armoredCore6: { cover: STEAM_COVER(1888160), hero: STEAM_HERO(1888160) },
  liesOfP:     { cover: STEAM_COVER(1627720), hero: STEAM_HERO(1627720) },
  helldivers2: { cover: STEAM_COVER(553850),  hero: STEAM_HERO(553850) },
  dragonsDogma2: { cover: STEAM_COVER(2054970), hero: STEAM_HERO(2054970) },
  p5r:         { cover: STEAM_COVER(1687950), hero: STEAM_HERO(1687950) },
  acValhalla:  { cover: STEAM_COVER(2208920), hero: STEAM_HERO(2208920) },
};

export const MOCK_GAMES: Game[] = [
  {
    id: 1, slug: "cyberpunk-2077", name: "赛博朋克 2077",
    released: "2020-12-10",
    background_image: IMG.cyberpunk.cover, hero_image: IMG.cyberpunk.hero,
    rating: 4.2, metacritic: 86,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 2, slug: "elden-ring", name: "艾尔登法环",
    released: "2022-02-25",
    background_image: IMG.eldenRing.cover, hero_image: IMG.eldenRing.hero,
    rating: 4.7, metacritic: 96,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 11, name: "魂系", slug: "souls-like" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 3, slug: "god-of-war-ragnarok", name: "战神: 诸神黄昏",
    released: "2022-11-09",
    background_image: IMG.gowRagnarok.cover, hero_image: IMG.gowRagnarok.hero,
    rating: 4.6, metacritic: 94,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 4, slug: "baldurs-gate-3", name: "博德之门 3",
    released: "2023-08-03",
    background_image: IMG.baldursGate3.cover, hero_image: IMG.baldursGate3.hero,
    rating: 4.8, metacritic: 96,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 5, name: "策略", slug: "strategy" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 5, slug: "red-dead-redemption-2", name: "荒野大镖客: 救赎 2",
    released: "2018-10-26",
    background_image: IMG.rdr2.cover, hero_image: IMG.rdr2.hero,
    rating: 4.5, metacritic: 97,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 6, slug: "the-witcher-3", name: "巫师 3: 狂猎",
    released: "2015-05-19",
    background_image: IMG.witcher3.cover, hero_image: IMG.witcher3.hero,
    rating: 4.6, metacritic: 93,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }, { platform: { id: 4, name: "Nintendo Switch", slug: "nintendo-switch" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 7, slug: "spider-man-2", name: "漫威蜘蛛侠 2",
    released: "2023-10-20",
    background_image: IMG.spiderMan2.cover, hero_image: IMG.spiderMan2.hero,
    rating: 4.4, metacritic: 90,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 8, slug: "zelda-tears-of-the-kingdom", name: "塞尔达传说: 王国之泪",
    released: "2023-05-12",
    background_image: IMG.zeldaTotK.cover, hero_image: IMG.zeldaTotK.hero,
    rating: 4.7, metacritic: 91,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }],
    platforms: [{ platform: { id: 4, name: "Nintendo Switch", slug: "nintendo-switch" }, requirements: {} }],
    esrb_rating: { name: "Everyone 10+" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 9, slug: "resident-evil-4-remake", name: "生化危机 4 重制版",
    released: "2023-03-24",
    background_image: IMG.re4Remake.cover, hero_image: IMG.re4Remake.hero,
    rating: 4.3, metacritic: 92,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 6, name: "射击", slug: "shooter" }, { id: 12, name: "恐怖", slug: "horror" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 10, slug: "starfield", name: "星空",
    released: "2023-09-06",
    background_image: IMG.starfield.cover, hero_image: IMG.starfield.hero,
    rating: 3.8, metacritic: 83,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 13, name: "科幻", slug: "sci-fi" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 5, name: "Xbox Series X", slug: "xbox-series-x" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 11, slug: "horizon-forbidden-west", name: "地平线: 西之绝境",
    released: "2022-02-18",
    background_image: IMG.horizonFW.cover, hero_image: IMG.horizonFW.hero,
    rating: 4.3, metacritic: 88,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 12, slug: "black-myth-wukong", name: "黑神话: 悟空",
    released: "2024-08-20",
    background_image: IMG.blackMyth.cover, hero_image: IMG.blackMyth.hero,
    rating: 4.5, metacritic: 90,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 14, name: "神话", slug: "mythology" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 13, slug: "gta-5", name: "侠盗猎车手 5",
    released: "2015-04-14",
    background_image: IMG.gta5.cover, hero_image: IMG.gta5.hero,
    rating: 4.5, metacritic: 96,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }, { platform: { id: 5, name: "Xbox One", slug: "xbox-one" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 14, slug: "monster-hunter-world", name: "怪物猎人: 世界",
    released: "2018-08-09",
    background_image: IMG.mhw.cover, hero_image: IMG.mhw.hero,
    rating: 4.5, metacritic: 90,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 15, slug: "sekiro", name: "只狼: 影逝二度",
    released: "2019-03-22",
    background_image: IMG.sekiro.cover, hero_image: IMG.sekiro.hero,
    rating: 4.6, metacritic: 90,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 11, name: "魂系", slug: "souls-like" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 16, slug: "dark-souls-3", name: "黑暗之魂 3",
    released: "2016-04-12",
    background_image: IMG.darkSouls3.cover, hero_image: IMG.darkSouls3.hero,
    rating: 4.5, metacritic: 89,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 11, name: "魂系", slug: "souls-like" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 17, slug: "ghost-of-tsushima", name: "对马岛之魂",
    released: "2024-05-16",
    background_image: IMG.ghostTsushima.cover, hero_image: IMG.ghostTsushima.hero,
    rating: 4.6, metacritic: 83,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 18, slug: "death-stranding", name: "死亡搁浅",
    released: "2022-03-30",
    background_image: IMG.deathStranding.cover, hero_image: IMG.deathStranding.hero,
    rating: 4.3, metacritic: 86,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 19, slug: "hades", name: "黑帝斯",
    released: "2020-09-17",
    background_image: IMG.hades.cover, hero_image: IMG.hades.hero,
    rating: 4.7, metacritic: 93,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 15, name: "独立", slug: "indie" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 4, name: "Nintendo Switch", slug: "nintendo-switch" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 20, slug: "hogwarts-legacy", name: "霍格沃茨之遗",
    released: "2023-02-10",
    background_image: IMG.hogwarts.cover, hero_image: IMG.hogwarts.hero,
    rating: 4.4, metacritic: 83,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 21, slug: "doom-eternal", name: "毁灭战士: 永恒",
    released: "2020-03-20",
    background_image: IMG.doomEternal.cover, hero_image: IMG.doomEternal.hero,
    rating: 4.5, metacritic: 89,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 6, name: "射击", slug: "shooter" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 22, slug: "stray", name: "迷失",
    released: "2022-07-19",
    background_image: IMG.stray.cover, hero_image: IMG.stray.hero,
    rating: 4.4, metacritic: 83,
    genres: [{ id: 3, name: "冒险", slug: "adventure" }, { id: 15, name: "独立", slug: "indie" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Everyone 10+" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 23, slug: "ff7-remake", name: "最终幻想 7 重制版",
    released: "2022-06-17",
    background_image: IMG.ff7r.cover, hero_image: IMG.ff7r.hero,
    rating: 4.5, metacritic: 89,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 1, name: "动作", slug: "action" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 24, slug: "diablo-4", name: "暗黑破坏神 4",
    released: "2023-06-06",
    background_image: IMG.diablo4.cover, hero_image: IMG.diablo4.hero,
    rating: 3.8, metacritic: 86,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 25, slug: "armored-core-6", name: "装甲核心 6",
    released: "2023-08-25",
    background_image: IMG.armoredCore6.cover, hero_image: IMG.armoredCore6.hero,
    rating: 4.4, metacritic: 86,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 6, name: "射击", slug: "shooter" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 26, slug: "lies-of-p", name: "匹诺曹的谎言",
    released: "2023-09-19",
    background_image: IMG.liesOfP.cover, hero_image: IMG.liesOfP.hero,
    rating: 4.3, metacritic: 80,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 11, name: "魂系", slug: "souls-like" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 27, slug: "helldivers-2", name: "地狱潜兵 2",
    released: "2024-02-08",
    background_image: IMG.helldivers2.cover, hero_image: IMG.helldivers2.hero,
    rating: 4.4, metacritic: 82,
    genres: [{ id: 6, name: "射击", slug: "shooter" }, { id: 1, name: "动作", slug: "action" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 28, slug: "dragons-dogma-2", name: "龙之信条 2",
    released: "2024-03-22",
    background_image: IMG.dragonsDogma2.cover, hero_image: IMG.dragonsDogma2.hero,
    rating: 3.8, metacritic: 86,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 29, slug: "persona-5-royal", name: "女神异闻录 5 皇家版",
    released: "2022-10-21",
    background_image: IMG.p5r.cover, hero_image: IMG.p5r.hero,
    rating: 4.7, metacritic: 95,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 5, name: "策略", slug: "strategy" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 4, name: "Nintendo Switch", slug: "nintendo-switch" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 30, slug: "ac-valhalla", name: "刺客信条: 英灵殿",
    released: "2020-11-10",
    background_image: IMG.acValhalla.cover, hero_image: IMG.acValhalla.hero,
    rating: 4.0, metacritic: 83,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
];
