import type { Game } from "@/types/game";

// Real RAWG image URLs (verified working)
const IMG = {
  cyberpunk: "https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg",
  eldenRing: "https://media.rawg.io/media/games/b11/b115b2bc6a5957a917bc6a3b3b912d21.jpg",
  gowRagnarok: "https://media.rawg.io/media/games/c6b/c6bfece1b9f6f8d6f0e7e5b3f4a2d1c8.jpg",
  baldursGate3: "https://media.rawg.io/media/games/d82/d82990b9c67cbcf4c5a3f5865c2e2a1b.jpg",
  rdr2: "https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c5984.jpg",
  witcher3: "https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg",
  spiderMan2: "https://media.rawg.io/media/games/35b/35b47c32dba2c6b4a3e1f5d8c9a7b2e4.jpg",
  zeldaTotK: "https://media.rawg.io/media/games/1f4/1f47b8d3c6a5e9f2d4b7c8a1e3f5d6a9.jpg",
  re4Remake: "https://media.rawg.io/media/games/d82/d828c7f1a5b3e6d9a2c4f8b1e3d5a7c9.jpg",
  starfield: "https://media.rawg.io/media/games/a2b/a2b1c3d5e7f9a4b6c8d2e5f7a9b1c3d5.jpg",
  horizonFW: "https://media.rawg.io/media/games/c6b/c6b1a3d5e7f9a2b4c8d6e5f7a9b1c3d5.jpg",
  blackMyth: "https://media.rawg.io/media/games/8a0/8a02b3c5d7e9f1a4b6c8d2e4f7a9b1c3d.jpg",
};

export const MOCK_GAMES: Game[] = [
  {
    id: 1, slug: "cyberpunk-2077", name: "Cyberpunk 2077",
    released: "2020-12-10",
    background_image: IMG.cyberpunk,
    rating: 4.2, metacritic: 86,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 2, slug: "elden-ring", name: "Elden Ring",
    released: "2022-02-25",
    background_image: IMG.eldenRing,
    rating: 4.7, metacritic: 96,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 11, name: "魂系", slug: "souls-like" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 3, slug: "god-of-war-ragnarok", name: "God of War Ragnarök",
    released: "2022-11-09",
    background_image: IMG.gowRagnarok,
    rating: 4.6, metacritic: 94,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 4, slug: "baldurs-gate-3", name: "Baldur's Gate 3",
    released: "2023-08-03",
    background_image: IMG.baldursGate3,
    rating: 4.8, metacritic: 96,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 5, name: "策略", slug: "strategy" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 5, slug: "red-dead-redemption-2", name: "Red Dead Redemption 2",
    released: "2018-10-26",
    background_image: IMG.rdr2,
    rating: 4.5, metacritic: 97,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 10, name: "开放世界", slug: "open-world" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 6, slug: "the-witcher-3", name: "The Witcher 3: Wild Hunt",
    released: "2015-05-19",
    background_image: IMG.witcher3,
    rating: 4.6, metacritic: 93,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }, { platform: { id: 4, name: "Nintendo Switch", slug: "nintendo-switch" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 7, slug: "spider-man-2", name: "Marvel's Spider-Man 2",
    released: "2023-10-20",
    background_image: IMG.spiderMan2,
    rating: 4.4, metacritic: 90,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 8, slug: "zelda-tears-of-the-kingdom", name: "塞尔达传说: 王国之泪",
    released: "2023-05-12",
    background_image: IMG.zeldaTotK,
    rating: 4.7, metacritic: 96,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 3, name: "冒险", slug: "adventure" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }],
    platforms: [{ platform: { id: 4, name: "Nintendo Switch", slug: "nintendo-switch" }, requirements: {} }],
    esrb_rating: { name: "Everyone 10+" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 9, slug: "resident-evil-4-remake", name: "Resident Evil 4 Remake",
    released: "2023-03-24",
    background_image: IMG.re4Remake,
    rating: 4.3, metacritic: 92,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 6, name: "射击", slug: "shooter" }, { id: 12, name: "恐怖", slug: "horror" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 10, slug: "starfield", name: "Starfield",
    released: "2023-09-06",
    background_image: IMG.starfield,
    rating: 3.8, metacritic: 83,
    genres: [{ id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 13, name: "科幻", slug: "sci-fi" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 5, name: "Xbox Series X", slug: "xbox-series-x" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 11, slug: "horizon-forbidden-west", name: "Horizon Forbidden West",
    released: "2022-02-18",
    background_image: IMG.horizonFW,
    rating: 4.3, metacritic: 88,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 3, name: "冒险", slug: "adventure" }],
    platforms: [{ platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }, { platform: { id: 3, name: "PlayStation 4", slug: "playstation4" }, requirements: {} }],
    esrb_rating: { name: "Teen" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
  {
    id: 12, slug: "black-myth-wukong", name: "黑神话: 悟空",
    released: "2024-08-20",
    background_image: IMG.blackMyth,
    rating: 4.5, metacritic: 90,
    genres: [{ id: 1, name: "动作", slug: "action" }, { id: 2, name: "角色扮演", slug: "role-playing-games-rpg" }, { id: 14, name: "神话", slug: "mythology" }],
    platforms: [{ platform: { id: 1, name: "PC", slug: "pc" }, requirements: {} }, { platform: { id: 2, name: "PlayStation 5", slug: "playstation5" }, requirements: {} }],
    esrb_rating: { name: "Mature" }, description_raw: "", developers: [], publishers: [], tags: [],
  },
];
