name = "gamehub"
main = "worker/index.ts"
compatibility_date = "2025-05-15"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "RAW_GAMES_KV"
id = "89d042301f2d49a384bc98fe70ae36a7"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "33963cd7d1c6464c9880c7160d5f8f65"

pages_build_output_dir = "out"

[observability]
enabled = true
